apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyapp
spec:
  selector:
    matchLabels:
      app: surveyapp
  replicas: 1
  template:
    metadata:
      labels:
        app: surveyapp
    spec:
      containers:
      - name: swe645
        image: asdpkp/swe645hw3:yolo
        ports:
          - containerPort: 8080
        env: 
          - name: DB_HOST
            value: mysqldbi

          - name: DB_NAME
            value: student_surveydb

          - name: DB_USERNAME
            value: root

          - name: DB_PASSWORD
            value: root


---

apiVersion: v1
kind: Service
metadata:
  name: surveyapp-svc
spec:
  selector:
    app: surveyapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
