apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldbi
  labels:
    app: mysqldbi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysqldbi
  template:
    metadata:
      labels:
        app: mysqldbi
        tier: database
    spec:
      containers:
        - name: mysqldbi
          image: mysql
          imagePullPolicy: "IfNotPresent"
          env: 
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: surveysdb
          ports:
          - containerPort: 3307
            name: mysqldbi
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mypvc
      
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: mypvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  labels:
    app: mysqldbi
    tier: database
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
