apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-instance
  labels:
    app: mysqldbi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysqldbi
  template:
    metadata:
      labels:
        app: mysqldbi
    spec:
      containers:
        - name: mysqldb
          image: mysql
          env: 
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: surveysdb
          ports:
          - containerPort: 80


