apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysqldbi
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldbi
  labels:
    app: mysqldbi
    tier: database
spec:
  selector:
    matchLabels:
      app: mysqldbi
  template:
    metadata:
      labels:
        app: mysqldbi
        tier: database
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: mysqldbi
          tier: database
    spec:
      containers:
        - name: mysqldbi
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root

            - name: MYSQL_DATABASE
              value: mysqldb

          ports:
            - containerPort: 3306
              name: mysqldb

          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-persistent-storage
          persistenVolumeClain:
            claimName: mysql-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: mysqldbi
  labels:
    app: mysqldbi
    tier: database
spec:
  selector:
    app: mysqldbi
    tier: database
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
