apiVersion: v1
kind: Service
metadata:
  name: mysqldbi
  labels:
    app: mysqldbi
    tier: database
spec:
  type: NodePort
  selector:
    app: mysqldbi
    tier: database
  ports:
  - port: 3306
    nodePort: 3306
    targetPort: 3306
